basePath: /
definitions:
  main.Song:
    properties:
      group:
        type: string
      id_group:
        type: integer
      id_song:
        type: integer
      link:
        type: string
      release_date:
        type: string
      song:
        type: string
      text:
        type: string
    type: object
  main.SongDetail:
    properties:
      link:
        type: string
      release_date:
        type: string
      text:
        type: string
    type: object
  main.SongShort:
    properties:
      group:
        type: string
      song:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Online Music Library API project.
  title: OnlineMusicLibrary API
  version: "1.0"
paths:
  /info:
    get:
      consumes:
      - application/json
      description: Get releaseDate, text, link for a song based on group and song.
      parameters:
      - description: Group of the song
        in: query
        name: group
        required: true
        type: string
      - description: Title of the song
        in: query
        name: song
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Song details
          schema:
            $ref: '#/definitions/main.SongDetail'
        "400":
          description: Missing required parameters 'group' or 'song'
          schema:
            type: string
        "404":
          description: Song not found
          schema:
            type: string
        "500":
          description: Failed to fetch song details
          schema:
            type: string
      summary: Music info
      tags:
      - songs
  /songs:
    delete:
      consumes:
      - application/json
      description: Delete a song from the database by its ID.
      parameters:
      - description: ID of the song
        in: query
        name: id_song
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid parameters
          schema:
            type: string
        "404":
          description: Song not found
          schema:
            type: string
        "500":
          description: Failed to delete song
          schema:
            type: string
      summary: Delete a song
      tags:
      - songs
    get:
      consumes:
      - application/json
      description: 'Retrieve a list of songs with optional filters: group name, song
        name, release date, text, link.'
      parameters:
      - description: Filter by group name
        in: query
        name: group
        type: string
      - description: Filter by song name
        in: query
        name: song
        type: string
      - description: Filter by release date (YYYY-MM-DD)
        in: query
        name: release_date
        type: string
      - description: Filter by text
        in: query
        name: text
        type: string
      - description: Filter by link
        in: query
        name: link
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Filtered list of songs
          schema:
            items:
              $ref: '#/definitions/main.Song'
            type: array
        "500":
          description: Failed to fetch songs
          schema:
            type: string
      summary: Get songs with optional filters and pagination
      tags:
      - songs
    post:
      consumes:
      - application/json
      description: Add a new song by providing group name and song name. Details (release
        date, text, link) are fetched from an external API.
      parameters:
      - description: Group and Song names
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/main.SongShort'
      produces:
      - application/json
      responses:
        "201":
          description: Song added successfully
          schema:
            type: string
        "400":
          description: Invalid input
          schema:
            type: string
        "404":
          description: Song details not found
          schema:
            type: string
        "500":
          description: Failed to add song
          schema:
            type: string
      summary: Add a new song
      tags:
      - songs
    put:
      consumes:
      - application/json
      description: Update the details of an existing song.
      parameters:
      - description: ID of the song
        in: query
        name: id_song
        required: true
        type: integer
      - description: Updated song details
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/main.Song'
      produces:
      - application/json
      responses:
        "200":
          description: The updated song
          schema:
            $ref: '#/definitions/main.Song'
        "400":
          description: Invalid input
          schema:
            type: string
        "404":
          description: Song not found
          schema:
            type: string
        "500":
          description: Failed to update song
          schema:
            type: string
      summary: Update song details
      tags:
      - songs
  /songs/text:
    get:
      consumes:
      - application/json
      description: Fetch the song text with pagination by verses.
      parameters:
      - description: ID of the song
        in: query
        name: id_song
        required: true
        type: integer
      - description: Page number (default is 1)
        in: query
        name: page
        type: integer
      - description: Number of verses per page (default is 1)
        in: query
        name: limit
        type: integer
      produces:
      - text/plain
      responses:
        "200":
          description: Song text or a portion of it
          schema:
            type: string
        "400":
          description: Invalid parameters
          schema:
            type: string
        "404":
          description: Song not found or no text available
          schema:
            type: string
        "500":
          description: Failed to fetch song text
          schema:
            type: string
      summary: Get song text with pagination
      tags:
      - songs
swagger: "2.0"
